-- =========================================================
-- BOVARY NOW
-- SUPABASE DATABASE SCHEMA
-- =========================================================
--
-- This file documents the current database configuration.
-- Do not expose Supabase secret/service keys here.
--
-- Project:
-- Bovary Now
--
-- Main tables:
--   public.events
--   public.announcements
--   public.admins
--
-- Storage bucket:
--   event-banners
--
-- =========================================================


-- =========================================================
-- EVENTS
-- =========================================================

CREATE TABLE IF NOT EXISTS public.events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    image_url TEXT,
    event_date DATE NOT NULL,
    event_time TIME NOT NULL,
    timezone TEXT NOT NULL DEFAULT 'America/Sao_Paulo',
    host TEXT,
    status TEXT NOT NULL DEFAULT 'scheduled',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- =========================================================
-- ANNOUNCEMENTS
-- =========================================================

CREATE TABLE IF NOT EXISTS public.announcements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- =========================================================
-- ADMINS
-- =========================================================

CREATE TABLE IF NOT EXISTS public.admins (
    user_id UUID PRIMARY KEY
        REFERENCES auth.users(id)
        ON DELETE CASCADE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- =========================================================
-- ROW LEVEL SECURITY
-- =========================================================

ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.admins ENABLE ROW LEVEL SECURITY;


-- =========================================================
-- ADMIN CHECK FUNCTION
-- =========================================================

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN
LANGUAGE SQL
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT EXISTS (
        SELECT 1
        FROM public.admins
        WHERE user_id = auth.uid()
    );
$$;


-- =========================================================
-- EVENTS — PUBLIC READ
-- =========================================================

DROP POLICY IF EXISTS "Public can view events"
ON public.events;

CREATE POLICY "Public can view events"
ON public.events
FOR SELECT
TO anon, authenticated
USING (true);


-- =========================================================
-- EVENTS — ADMIN WRITE
-- =========================================================

DROP POLICY IF EXISTS "Admins can insert events"
ON public.events;

CREATE POLICY "Admins can insert events"
ON public.events
FOR INSERT
TO authenticated
WITH CHECK (
    public.is_admin()
);


DROP POLICY IF EXISTS "Admins can update events"
ON public.events;

CREATE POLICY "Admins can update events"
ON public.events
FOR UPDATE
TO authenticated
USING (
    public.is_admin()
)
WITH CHECK (
    public.is_admin()
);


DROP POLICY IF EXISTS "Admins can delete events"
ON public.events;

CREATE POLICY "Admins can delete events"
ON public.events
FOR DELETE
TO authenticated
USING (
    public.is_admin()
);


-- =========================================================
-- ADMINS — OWN RECORD
-- =========================================================

DROP POLICY IF EXISTS "Admins can view their own record"
ON public.admins;

CREATE POLICY "Admins can view their own record"
ON public.admins
FOR SELECT
TO authenticated
USING (
    user_id = auth.uid()
);


-- =========================================================
-- STORAGE
-- Bucket:
-- event-banners
-- =========================================================

DROP POLICY IF EXISTS "Admins can upload event banners"
ON storage.objects;

CREATE POLICY "Admins can upload event banners"
ON storage.objects
FOR INSERT
TO authenticated
WITH CHECK (
    bucket_id = 'event-banners'
    AND public.is_admin()
);


DROP POLICY IF EXISTS "Admins can update event banners"
ON storage.objects;

CREATE POLICY "Admins can update event banners"
ON storage.objects
FOR UPDATE
TO authenticated
USING (
    bucket_id = 'event-banners'
    AND public.is_admin()
)
WITH CHECK (
    bucket_id = 'event-banners'
    AND public.is_admin()
);


DROP POLICY IF EXISTS "Admins can delete event banners"
ON storage.objects;

CREATE POLICY "Admins can delete event banners"
ON storage.objects
FOR DELETE
TO authenticated
USING (
    bucket_id = 'event-banners'
    AND public.is_admin()
);


DROP POLICY IF EXISTS "Admins can view event banner objects"
ON storage.objects;

CREATE POLICY "Admins can view event banner objects"
ON storage.objects
FOR SELECT
TO authenticated
USING (
    bucket_id = 'event-banners'
    AND public.is_admin()
);


-- =========================================================
-- END
-- =========================================================


-- =========================================================
-- FENRIR YAKUZA (FiveM) — used by Android app tab "FiveM"
-- =========================================================

CREATE TABLE IF NOT EXISTS public.fenrir_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    image_url TEXT,
    event_date DATE NOT NULL,
    event_time TIME NOT NULL,
    timezone TEXT NOT NULL DEFAULT 'America/Sao_Paulo',
    host TEXT,
    status TEXT NOT NULL DEFAULT 'scheduled',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.fenrir_announcements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.fenrir_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fenrir_announcements ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "fenrir_events_select_anon" ON public.fenrir_events;
CREATE POLICY "fenrir_events_select_anon"
  ON public.fenrir_events FOR SELECT TO anon USING (true);

DROP POLICY IF EXISTS "fenrir_announcements_select_anon" ON public.fenrir_announcements;
CREATE POLICY "fenrir_announcements_select_anon"
  ON public.fenrir_announcements FOR SELECT TO anon USING (true);

DROP POLICY IF EXISTS "fenrir_events_admin_all" ON public.fenrir_events;
CREATE POLICY "fenrir_events_admin_all"
  ON public.fenrir_events FOR ALL TO authenticated
  USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "fenrir_announcements_admin_all" ON public.fenrir_announcements;
CREATE POLICY "fenrir_announcements_admin_all"
  ON public.fenrir_announcements FOR ALL TO authenticated
  USING (public.is_admin()) WITH CHECK (public.is_admin());
