-- =========================================================
-- BOVARY NOW
-- SUPABASE DATABASE SCHEMA
-- =========================================================
--
-- This file documents the current database configuration.
-- Do not expose Supabase secret/service keys here.
--
-- Project:
-- Bovary Now
--
-- Main tables:
--   public.events
--   public.announcements
--   public.admins
--
-- Storage bucket:
--   event-banners
--
-- =========================================================


-- =========================================================
-- EVENTS
-- =========================================================

CREATE TABLE IF NOT EXISTS public.events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    image_url TEXT,
    event_date DATE NOT NULL,
    event_time TIME NOT NULL,
    timezone TEXT NOT NULL DEFAULT 'America/Sao_Paulo',
    host TEXT,
    status TEXT NOT NULL DEFAULT 'scheduled',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- =========================================================
-- ANNOUNCEMENTS
-- =========================================================

CREATE TABLE IF NOT EXISTS public.announcements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- =========================================================
-- ADMINS
-- =========================================================

CREATE TABLE IF NOT EXISTS public.admins (
    user_id UUID PRIMARY KEY
        REFERENCES auth.users(id)
        ON DELETE CASCADE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- =========================================================
-- ROW LEVEL SECURITY
-- =========================================================

ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.admins ENABLE ROW LEVEL SECURITY;


-- =========================================================
-- ADMIN CHECK FUNCTION
-- =========================================================

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN
LANGUAGE SQL
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT EXISTS (
        SELECT 1
        FROM public.admins
        WHERE user_id = auth.uid()
    );
$$;


-- =========================================================
-- EVENTS — PUBLIC READ
-- =========================================================

DROP POLICY IF EXISTS "Public can view events"
ON public.events;

CREATE POLICY "Public can view events"
ON public.events
FOR SELECT
TO anon, authenticated
USING (true);


-- =========================================================
-- EVENTS — ADMIN WRITE
-- =========================================================

DROP POLICY IF EXISTS "Admins can insert events"
ON public.events;

CREATE POLICY "Admins can insert events"
ON public.events
FOR INSERT
TO authenticated
WITH CHECK (
    public.is_admin()
);


DROP POLICY IF EXISTS "Admins can update events"
ON public.events;

CREATE POLICY "Admins can update events"
ON public.events
FOR UPDATE
TO authenticated
USING (
    public.is_admin()
)
WITH CHECK (
    public.is_admin()
);


DROP POLICY IF EXISTS "Admins can delete events"
ON public.events;

CREATE POLICY "Admins can delete events"
ON public.events
FOR DELETE
TO authenticated
USING (
    public.is_admin()
);


-- =========================================================
-- ADMINS — OWN RECORD
-- =========================================================

DROP POLICY IF EXISTS "Admins can view their own record"
ON public.admins;

CREATE POLICY "Admins can view their own record"
ON public.admins
FOR SELECT
TO authenticated
USING (
    user_id = auth.uid()
);


-- =========================================================
-- STORAGE
-- Bucket:
-- event-banners
-- =========================================================

DROP POLICY IF EXISTS "Admins can upload event banners"
ON storage.objects;

CREATE POLICY "Admins can upload event banners"
ON storage.objects
FOR INSERT
TO authenticated
WITH CHECK (
    bucket_id = 'event-banners'
    AND public.is_admin()
);


DROP POLICY IF EXISTS "Admins can update event banners"
ON storage.objects;

CREATE POLICY "Admins can update event banners"
ON storage.objects
FOR UPDATE
TO authenticated
USING (
    bucket_id = 'event-banners'
    AND public.is_admin()
)
WITH CHECK (
    bucket_id = 'event-banners'
    AND public.is_admin()
);


DROP POLICY IF EXISTS "Admins can delete event banners"
ON storage.objects;

CREATE POLICY "Admins can delete event banners"
ON storage.objects
FOR DELETE
TO authenticated
USING (
    bucket_id = 'event-banners'
    AND public.is_admin()
);


DROP POLICY IF EXISTS "Admins can view event banner objects"
ON storage.objects;

CREATE POLICY "Admins can view event banner objects"
ON storage.objects
FOR SELECT
TO authenticated
USING (
    bucket_id = 'event-banners'
    AND public.is_admin()
);


-- =========================================================
-- END
-- =========================================================


-- =========================================================
-- FENRIR YAKUZA (FiveM) — used by Android app tab "FiveM"
-- =========================================================

CREATE TABLE IF NOT EXISTS public.fenrir_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    image_url TEXT,
    event_date DATE NOT NULL,
    event_time TIME NOT NULL,
    timezone TEXT NOT NULL DEFAULT 'America/Sao_Paulo',
    host TEXT,
    status TEXT NOT NULL DEFAULT 'scheduled',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.fenrir_announcements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.fenrir_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fenrir_announcements ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "fenrir_events_select_anon" ON public.fenrir_events;
CREATE POLICY "fenrir_events_select_anon"
  ON public.fenrir_events FOR SELECT TO anon USING (true);

DROP POLICY IF EXISTS "fenrir_announcements_select_anon" ON public.fenrir_announcements;
CREATE POLICY "fenrir_announcements_select_anon"
  ON public.fenrir_announcements FOR SELECT TO anon USING (true);

DROP POLICY IF EXISTS "fenrir_events_admin_all" ON public.fenrir_events;
CREATE POLICY "fenrir_events_admin_all"
  ON public.fenrir_events FOR ALL TO authenticated
  USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "fenrir_announcements_admin_all" ON public.fenrir_announcements;
CREATE POLICY "fenrir_announcements_admin_all"
  ON public.fenrir_announcements FOR ALL TO authenticated
  USING (public.is_admin()) WITH CHECK (public.is_admin());

-- =========================================================
-- AUTO-END HOURS (optional — admin panel auto-ends sessions)
-- Run once in Supabase SQL Editor if you want the value stored in DB.
-- App does not need this column; panel falls back to localStorage + default 5h.
-- =========================================================

ALTER TABLE public.events
  ADD COLUMN IF NOT EXISTS auto_end_hours INTEGER NOT NULL DEFAULT 5;

ALTER TABLE public.fenrir_events
  ADD COLUMN IF NOT EXISTS auto_end_hours INTEGER NOT NULL DEFAULT 5;


-- =========================================================
-- KEEP ALIVE / SILENT PULSE (anti-pause)
-- Run once in Supabase SQL Editor.
-- Used by admin panel buttons: PING and APP PULSE.
-- Does not affect member app UI (no visible rows/fields there).
-- =========================================================

CREATE TABLE IF NOT EXISTS public.keepalive (
  id INTEGER PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  last_ping_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  source TEXT DEFAULT 'unknown',
  note TEXT,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO public.keepalive (id, last_ping_at, source, note)
VALUES (1, NOW(), 'schema', 'initial')
ON CONFLICT (id) DO NOTHING;

ALTER TABLE public.keepalive ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "keepalive_select_all" ON public.keepalive;
CREATE POLICY "keepalive_select_all"
  ON public.keepalive FOR SELECT
  TO anon, authenticated
  USING (true);

DROP POLICY IF EXISTS "keepalive_write_all" ON public.keepalive;
CREATE POLICY "keepalive_write_all"
  ON public.keepalive FOR ALL
  TO anon, authenticated
  USING (true)
  WITH CHECK (true);

CREATE OR REPLACE FUNCTION public.ping_keepalive(
  p_source TEXT DEFAULT 'rpc',
  p_note TEXT DEFAULT NULL
)
RETURNS TIMESTAMPTZ
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  ts TIMESTAMPTZ := NOW();
BEGIN
  INSERT INTO public.keepalive (id, last_ping_at, source, note, updated_at)
  VALUES (1, ts, COALESCE(p_source, 'rpc'), p_note, ts)
  ON CONFLICT (id) DO UPDATE
    SET last_ping_at = EXCLUDED.last_ping_at,
        source = EXCLUDED.source,
        note = EXCLUDED.note,
        updated_at = EXCLUDED.updated_at;
  RETURN ts;
END;
$$;

GRANT EXECUTE ON FUNCTION public.ping_keepalive(TEXT, TEXT) TO anon, authenticated;
